---
title: This Diagram shows the relationship between all system components
---
classDiagram
    class C_0009984192897324832466["BankAccount"]
    class C_0009984192897324832466 {
        +BankAccount(int accountNumber, const std::string & accountHolder, const std::string & accountType, double accountBalance) : void
        +deposit(double amount) : void
        +displayAccountInfo() : [const] void
        +getAccountBalance() : [const] double
        +getAccountHolder() : [const] const std::string &
        +getAccountNumber() : [const] int
        +getAccountType() : [const] const std::string &
        +withdraw(double amount) : bool
        -accountBalance : double
        -accountHolder : std::string
        -accountNumber : int
        -accountType : std::string
    }
    click C_0009984192897324832466 href "classBankAccount.html" "BankAccount"
    class C_0013925658533498293399["Bank"]
    class C_0013925658533498293399 {
        +Bank() : void
        +Bank(Bank && obj) : void
        +SortAccounts() : void
        +addAccount(const BankAccount & account) : void
        +displayAllAccounts() : [const] void
        +getAccounts() : [const] std::vector&lt;BankAccount&gt;
        +getTotalBalance() : [const] double
        -accounts : std::vector&lt;BankAccount&gt;
    }
    click C_0013925658533498293399 href "classBank.html" "Bank"
    C_0013925658533498293399 o-- C_0009984192897324832466 : -accounts

%% Generated with clang-uml, version 0.5.3
%% LLVM version clang version 18.1.1 (https://github.com/llvm/llvm-project.git dba2a75e9c7ef81fe84774ba5eee5e67e01d801a)
